# Generated by Django 2.1.7 on 2019-04-10 08:09

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=200)),
                ('full_description', models.CharField(max_length=1000)),
                ('contact_person', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('business_fax', models.PositiveIntegerField(blank=True, max_length=128)),
                ('phone_number', models.PositiveIntegerField(max_length=128)),
                ('phone_number_second', models.PositiveIntegerField(blank=True, max_length=128)),
                ('zip_code', models.PositiveIntegerField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=150, populate_from='title', unique=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
    ]
