# Generated by Django 2.1.7 on 2019-09-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='business_fax',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone_number_second',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
